### ISSUE TITLE
Lang File Not Loaded.

### ISSUE THREAD

**Issue by Kingdomall** [XDelta/Seafaring#1]
I'm having this problem where Seafaring is not loading a file and thus can't launch the game. Is this a Forge issue?
![image](https://user-images.githubusercontent.com/45534238/66528737-da106b00-eab5-11e9-9ff8-98c399c7292e.png)

**Comment by XDelta** [comment]
Looks like you need to update your forge version to be higher than 28.1.0

**Comment by XDelta** [comment]
If your forge version is higher than 28.1.0 and you are still receiving this message, please include the forge version you have tried.
