### ISSUE TITLE
Fails to Load After Launch

### ISSUE THREAD

**Issue by WenXin20** [XDelta/Seafaring#2]
`Minecraft v1.14.4`
`Forge v28.2.0`
`Seafaring v0.1.52`

After launching the game, I got the following error after starting.
[Log](https://gist.github.com/WenXin20/88209ff1520d3cb391392a77d93f1d54)

**Comment by XDelta** [comment]
Looking into it, thanks for the report

**Comment by XDelta** [comment]
Update: released a new version for for 28.2.0+, I think I got the crash sorted out

**Comment by WenXin20** [comment]
Thanks! I'll try it out
